sudo: false
language: java
jdk:
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/joda/collect
# install
install:
  - mvn --version
script:
  - mvn install site -e -B
after_success:
  - if [[ $TRAVIS_TAG =~ ^website.*$ ]] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk10" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
  - if [[ $TRAVIS_TAG =~ ^v.*$ ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk10" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
# secure keys for GITHUB_TOKEN
env:
  global:
  - secure: G0LQgQPayjbN6TLoLtIkqljkBge8fIH1lRL4Mn+aroTgLgE60gaJJfWPc26wHwPKRP2bMSl5peQUEDLhJ/FA7G+o4HSrGzqU0h7PX2R6S7niYgPuSVUc/hhUWb0WFoterXSAbbS3IWkEkzHoXKizhTO6mffy8/E60ZzZ8gGHMqM=
