version: 2.1

executors:
  jdk11:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -XX:+PrintFlagsFinal

jobs:
  build:
    executor: jdk11
    steps:
      - run: ls -la /sys/fs/cgroup/memory/
      - run: cat /sys/fs/cgroup/memory/memory.limit_in_bytes
      - run: mvn --version
